# Generated by Django 5.0.6 on 2024-06-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_room_occupant_room_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_room', to='catalog.room'),
        ),
    ]
