# Generated by Django 5.0.6 on 2024-06-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_person_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='room',
        ),
    ]
