# Generated by Django 5.0.6 on 2024-06-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_person_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
