# Generated by Django 5.0.6 on 2024-06-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='preferences',
            field=models.CharField(choices=[('preference_open', 'Open to any guest'), ('preference_mid', 'Only known guests'), ('preference_strict', 'Only members')], default='preference_1', max_length=20),
        ),
    ]
