# Generated by Django 5.0.6 on 2024-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_person_preferences_person_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='guest_type',
            field=models.CharField(blank=True, choices=[('anyone', 'Anyone can stay here'), ('known_people', 'Only people well known to TO can stay here'), ('members', 'Only TO members can stay here')], default='anyone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='preference',
            field=models.CharField(choices=[('preference_open', 'Open to anyone'), ('preference_mid', 'Well known guests'), ('preference_strict', 'Members only')], default='preference_open', max_length=20),
        ),
    ]
