# Generated by Django 5.0.6 on 2024-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_customevent_guest_type_alter_person_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevent',
            name='guest_type',
            field=models.IntegerField(choices=[(1, 'Stranger'), (2, 'Known'), (3, 'Member')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='preference',
            field=models.IntegerField(choices=[(1, 'Anyone can stay here'), (2, 'Only people well known to TO can stay here'), (3, 'Only TO members can stay here')], default=1),
        ),
    ]
