# Generated by Django 5.0.6 on 2024-06-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_customevent_guest_type_alter_person_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevent',
            name='guest_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customevent',
            name='guest_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Stranger'), (2, 'Known'), (3, 'Member')], default=1, null=True),
        ),
    ]
