# Generated by Django 5.0.6 on 2024-07-02 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_calendar_alter_room_calendar'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
