# Generated by Django 5.0.6 on 2024-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_room_calendar_delete_customcalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='customevent',
            name='guest_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
