# Generated by Django 5.0.6 on 2024-07-04 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_remove_person_contact_email_and_more'),
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room', to='schedule.calendar'),
        ),
    ]
