# Generated by Django 5.0.6 on 2024-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_room_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
