# Generated by Django 5.0.6 on 2024-07-09 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_building_offline_room_offline_section_offline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='offline',
            new_name='is_offline',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='offline',
            new_name='is_offline',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='offline',
            new_name='is_offline',
        ),
        migrations.AlterField(
            model_name='section',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.building'),
        ),
    ]
