# Generated by Django 5.0.6 on 2024-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='area',
            field=models.CharField(default='not_courtyard', max_length=255),
            preserve_default=False,
        ),
    ]
